<Button>:
    font_size: 40
    color: 1, 0, 0, 1   #RGBA
    size_hint: 0.3, 0.5

<FloatLayout>
    Button:
        text: "Kamil"
        background_color: 0, 1, 0, 1
        #pos_hint: {"x", "y", "top", "bottom", "left", "right"}
        pos_hint:{"x":0.5, "top":0.9}

    Button:
        id: btn
        text: "Pies" if btn.state == "normal" else "Kot"
        background_color: 0, 0, 1, 1
        #pos_hint: {"x", "y", "top", "bottom", "left", "right"}
        pos: 140, 150
